model_name_or_path: Qwen/Qwen2.5-0.5B-Instruct
template: qwen
stage: sft
finetuning_type: lora
lora_rank: 16
dataset_dir: /kaggle/working/kaggle/LLM-finetune
dataset: persona
cutoff_len: 512
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 2.0e-4
num_train_epochs: 2.0
quantization_bit: 4
output_dir: /kaggle/working/qwen05-lora